# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ main ]
env:
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

jobs:   
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          curl --location --request POST 'https://hooks.slack.com/services/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' --header 'Accept: application/json' --header 'Content-Type: application/json' --data-raw '{ "blocks": [ { "type": "section", "text": { "type": "mrkdwn", "text": "`@${{ github.actor }}` has started developing `${GITHUB_REF##*/}` of `${{ github.repository }}` to Environment : *${{ github.job }}*" }, "accessory": { "type": "image", "image_url": "https://avatars.githubusercontent.com/${{ github.actor }}", "alt_text": "cute cat" } }, { "type": "divider" }, { "type": "header", "text": { "type": "plain_text", "text": "Deoplyment: ${{ job.status }}", "emoji": true } }, { "type": "divider" }, { "type": "context", "elements": [ { "type": "mrkdwn", "text": "*Pull request code* : ${{ github.event.number }} " } ] } ] }'
          
