# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
env:
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing requirements
      run: |
        pwd

    - name: Testing
      run: |
        Pytest
        
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      run: |
        echo ${{ job.status }}
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
